#!/bin/bash

# Load resources

xrdb -merge .Xresources

# Set up an icon tray

# trayer --edge top --align right --SetDockType true --SetPartialStrut true --expand true --width 10 --transparent true --tint 0x191970 --height 14 &
trayer --edge top --align right --SetDockType true --SetPartialStrut true --expand true --width 10 --transparent false --tint 0x191920 --height 17 &

# Set the background color<

xsetroot -solid midnightblue

# Fire up apps

xscreensaver -no-splash &

if [ -x /usr/bin/nm-applet ] ; then
   nm-applet --sm-disable &
fi

gnome-settings-daemon &

if [ -x /usr/bin/gnome-sound-applet ] ; then
   gnome-sound-applet &
fi

if [ -x /usr/bin/gnome-power-manager ] ; then
   sleep 3
   gnome-power-manager &
fi

redshift &

feh --bg-scale /home/oiad/docs/fotos/wallpapers/dar_dear.png

exec xmonad
